### ISSUE TITLE
converting from odk rboot project to Arduino

### ISSUE THREAD

**Issue by spants** [kzyapkov/esp-arduino-rboot#2]
Hi

I have about 40 devices around the world using Richard's RBOOT ota mechanism and I would like these devices to be updated with the new version of the program that I have written in the Arduino IDE. The flash layout on the existing code is:

0x000000 rBoot
0x001000 rBoot config

0x002000 rom1
0x080000 espfs1 (#define ESPFS_POS 0x80000 in httpdconfig.h)

0x202000 rom2
0x280000 espfs2 (same as above + 0x200000)

0x3f8000 user config (#define CFG_LOCATION 0x3f8 in user_config.h)
0x3fc000 sdk config

Do you think that it would be possible to do the change from ODK to Arduino via an OTA update? The current code downloads the bin and espfs files separately. I was thinking of maybe building a small stub program and dummy espfs files which downloads the actual program bin......

Also, did you update this to remove the update bug - does it affect this code? https://github.com/raburton/rboot/commit/75ca33be0524ab7a5f2bd55065add28ad812e045

**Comment by kzyapkov** [comment]
Hi,

It should be possible to do so, but your Arduino program should be built and linked for use with rboot, instead of their own eboot which works differently. I do this with a Makefile, but probably a better approach would be to fork the esp8266 arduino core and implement rboot support properly. I'd go for a small stub program as you suggest, which would take care of flashing the new bin/fs layout.

This project has not seen any updates in a looong time, and will probably not see any unless I find a good use for it. Use the sample here as an example, but do fetch the last rboot version and client code.

Also, I think rboot now supports Swing natively, and Cesanta use it for their mongoose-iot (formerly smart.js) project -- you may look at those for integration examples as well.
